//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP2010.Controls.AttachmentField.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SPAttachmentField {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SPAttachmentField() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SP2010.Controls.AttachmentField.Resources.SPAttachmentField", typeof(SPAttachmentField).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field to display of attachments of list items in list view. The following types of list can not be support the field: document library, image library, links, surveys. Created by Smart84 (http://www.codeplex.com/site/users/view/smart84).
        /// </summary>
        internal static string Feature_Description {
            get {
                return ResourceManager.GetString("Feature_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom field to display attachments of list items in list view.
        /// </summary>
        internal static string Feature_Name {
            get {
                return ResourceManager.GetString("Feature_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display attachments (list view).
        /// </summary>
        internal static string FieldType_DisplayName {
            get {
                return ResourceManager.GetString("FieldType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field already exists in the list.
        /// </summary>
        internal static string FieldType_Editor_CheckExists_Validation {
            get {
                return ResourceManager.GetString("FieldType_Editor_CheckExists_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following types of list can not be support the field: document library, image library, links, surveys..
        /// </summary>
        internal static string FieldType_Editor_CheckLibrary_Validation {
            get {
                return ResourceManager.GetString("FieldType_Editor_CheckLibrary_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field to display of attachments of list items in list view. The following types of list can not be support the field: document library, image library, links, surveys. Created by &lt;a href=&quot;http://www.codeplex.com/site/users/view/smart84&quot;&gt;Smart84&lt;/a&gt;.
        /// </summary>
        internal static string FieldType_Editor_Description {
            get {
                return ResourceManager.GetString("FieldType_Editor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of the field.
        /// </summary>
        internal static string FieldType_Editor_InputForm_LabelText {
            get {
                return ResourceManager.GetString("FieldType_Editor_InputForm_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No attachments.
        /// </summary>
        internal static string FieldType_NoAttachmants {
            get {
                return ResourceManager.GetString("FieldType_NoAttachmants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img src=&quot;/_layouts/images/info16by16.gif&quot; /&gt;&amp;nbsp;&lt;span style=&quot;position:relative;top:-4px;&quot;&gt;No display (only in list view)&lt;/span&gt;.
        /// </summary>
        internal static string FieldType_NoDisplay {
            get {
                return ResourceManager.GetString("FieldType_NoDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img src=&quot;/_layouts/images/info16by16.gif&quot; /&gt;&amp;nbsp;&lt;span style=&quot;position:relative;top:-4px;&quot;&gt;Not editable&lt;/span&gt;.
        /// </summary>
        internal static string FieldType_NoEdit {
            get {
                return ResourceManager.GetString("FieldType_NoEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display attachments (list view).
        /// </summary>
        internal static string FieldType_ShortDescription {
            get {
                return ResourceManager.GetString("FieldType_ShortDescription", resourceCulture);
            }
        }
    }
}
